version: '2'
services:
  db:
    build: ./db
    expose:
      - "3306"
    ports:
      - "3306:3306"
  jenkins:
    build: ./jenkins
    expose:
      - "8080"
    ports:
      - "10001:8080"
  localstack-s3:
    image: localstack/localstack:latest
    container_name: localstack-s3
    environment:
      - SERVICES=s3:5002
      - DEFAULT_REGION=eu-west-2
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "5002:5002"
      - "9999:8080"
